# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rachel Lin | UX Designer
email: rachellin@berkeley.edu
logo: logo.svg
description: > # this means to ignore newlines until "baseurl:"
  Rachel Lin | Designer + Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: rchlelle
github_username:  rachelelle

social:
  - title: linkedin
    url: http://linkedin.com/in/linrac
  - title: medium
    url: https://medium.com/@rachellin
  - title: github
    url: http://github.com/rachelelle
  - title: twitter
    url: http://twitter.com/rchlelle

# Build settings
markdown: kramdown
permalink: /:title/
